Move to rich for logging
janaSunrise/ZeroCOM pull request #5
Opened 2022-07-10 17:52 UTC by janaSunrise

Move to the `RichHandler` available for the `logging` module in Python instead of using the `coloredlogs` dependency (optional).

2022-07-10 22:40 UTC, ItsDrike requested changes
Also, don't forget to remove the `coloredlogs` dependency from `pyproject.toml`.

2022-07-10 22:40 UTC, ItsDrike commented on zerocom/utils/log.py
> +    )
Why use basic config? We're already setting everything manually. The log level is set on line 34 and there's already a `log_formatter` crated with the format, so we should be able to just add that formatter for the rich handler, just like adding a formatter for any log handler and then add that handler to the root log directly.

```py
rich_handler = RichHandler(show_time=False)
rich_handler.setFormatter(log_formatter)
root_log.addHandler(rich_handler)
```

2022-07-12 14:14 UTC, janaSunrise commented on zerocom/utils/log.py
> +    )
I've done this based on the rich logging docs - I'll update to this and test it out if it works and let you know!

2022-07-17 13:46 UTC, ItsDrike approved these changes

2022-07-17 14:23 UTC, merged